name: Publish Multiple Releases
run-name: Publish v${{ inputs.mod_version }} build(s) from ${{ inputs.branches }}

on:
  workflow_dispatch:
    inputs:
      mod_version:
        description: "Mod version (without v or -MC)"
        required: true
        type: string
      branches:
        description: "Space-separated list of branches to publish from"
        required: true
        type: string
      publish_curseforge:
        description: "Publish to CurseForge"
        required: true
        type: boolean
        default: true
      publish_modrinth:
        description: "Publish to Modrinth"
        required: true
        type: boolean
        default: true
      announce_update:
        description: "Announce as an update on WurstForum"
        required: true
        type: boolean
        default: false
      announce_ports:
        description: "Announce as ports on WurstForum"
        required: true
        type: boolean
        default: false
      dry_run:
        description: "Dry-run mode (don't actually publish anything)"
        required: false
        type: boolean
        default: false

permissions:
  # Needed to trigger the publish workflow.
  actions: write

jobs:

  prepare:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.set_branches.outputs.branches }}
    steps:
    - name: Convert branches input to JSON array
      id: set_branches
      run: |
        branches_array=(${{ inputs.branches }})
        quoted_branches=$(printf '"%s",' "${branches_array[@]}")
        JSON_ARRAY="[${quoted_branches%,}]"
        echo "branches=$JSON_ARRAY" >> "$GITHUB_OUTPUT"
        echo "Branches: $JSON_ARRAY" >> "$GITHUB_STEP_SUMMARY"

  publish_each:
    runs-on: ubuntu-latest
    needs: prepare
    if: ${{ !fromJson(inputs.dry_run) }}
    strategy:
      # Each job pushes an automated commit to wimods.net@master, so running them all in parallel
      # would likely cause conflicts. Also, various servers might hit rate limits if we just upload
      # all of the files at once.
      max-parallel: 1
      # If something goes wrong, all published files have to be manually deleted.
      # Best to fail as early as possible.
      fail-fast: true
      matrix:
        branch: ${{ fromJson(needs.prepare.outputs.branches) }}
    # TODO: Maybe also verify that the mod_version in each branch is as expected before publishing?
    steps:
    - name: Trigger publish workflow
      uses: Wurst-Imperium/dispatch-and-wait@v1
      with:
        token: ${{ github.token }}
        owner: ${{ github.repository_owner }}
        repo: ${{ github.event.repository.name }}
        ref: ${{ matrix.branch }}
        workflow: publish.yml
        workflow_inputs: |
          {
            "close_milestone": "true",
            "upload_backups": "true",
            "publish_github": "true",
            "publish_curseforge": "${{ inputs.publish_curseforge }}",
            "publish_modrinth": "${{ inputs.publish_modrinth }}",
            "update_website": "true"
          }
        run_timeout_seconds: 1800  # 30 minutes

  announce_update:
    runs-on: ubuntu-latest
    needs: [prepare, publish_each]
    if: ${{ !failure() && !cancelled() && inputs.announce_update }}
    steps:
    - name: Trigger announce workflow
      uses: Wurst-Imperium/dispatch-and-wait@v1
      with:
        token: ${{ secrets.WIMODS_NET_PUBLISH_TOKEN }}
        owner: Wurst-Imperium
        repo: wimods.net
        ref: master
        workflow: announce_mod_update.yml
        workflow_inputs: |
          {
            "mod": "wi-zoom",
            "mod_version": "${{ inputs.mod_version }}",
            "dry_run": "${{ inputs.dry_run }}"
          }
        run_timeout_seconds: 600  # 10 minutes

  announce_ports:
    runs-on: ubuntu-latest
    needs: [prepare, publish_each]
    if: ${{ !failure() && !cancelled() && inputs.announce_ports }}
    steps:
    - name: Trigger announce workflow
      uses: Wurst-Imperium/dispatch-and-wait@v1
      with:
        token: ${{ secrets.WIMODS_NET_PUBLISH_TOKEN }}
        owner: Wurst-Imperium
        repo: wimods.net
        ref: master
        workflow: announce_mod_ports.yml
        workflow_inputs: |
          {
            "mod": "wi-zoom",
            "mod_version": "${{ inputs.mod_version }}",
            "branches": "${{ inputs.branches }}",
            "dry_run": "${{ inputs.dry_run }}"
          }
        run_timeout_seconds: 600  # 10 minutes
